### Создание вакансии
POST http://localhost:7878/job-search/api/vacancies
Content-Type: application/json

{
  "id": null,
  "name": "vacancy 5",
  "city": "Perm",
  "requirements": "Req",
  "salaryFrom": "110000",
  "salaryTo": "150000"
}

### Обновление вакансии
PUT http://localhost:7878/job-search/api/vacancies/2
Content-Type: application/json

{
  "id": 7,
  "name": "vacancy 1.1",
  "city": "Perm",
  "requirements": "Req",
  "salaryFrom": "100000",
  "salaryTo": "180000"
}

### Получение списка вакансий
GET http://localhost:7878/job-search/api/v1/vacancies?search=pe

### Получение вакансии по Id
GET http://localhost:7878/job-search/api/v1/vacancies/1

### Удаление вакансии по Id
DELETE http://localhost:7878/job-search/api/v1/vacancies/2