### Создание вакансии
POST {{baseUrl}}/vacancies
Content-Type: application/json

{
  "id": null,
  "name": "vacancy 4",
  "city": "Perm",
  "requirements": "Req",
  "salaryFrom": "110000",
  "salaryTo": "150000"
}

### Обновление вакансии
PUT {{baseUrl}}/vacancies/2
Content-Type: application/json

{
  "id": 7,
  "name": "vacancy 1.1",
  "city": "Perm",
  "requirements": "Req",
  "salaryFrom": "100000",
  "salaryTo": "180000"
}

### Получение списка вакансий
GET {{baseUrl}}/vacancies

### Получение вакансии по Id
GET {{baseUrl}}/vacancies/1

### Удаление вакансии по Id
DELETE {{baseUrl}}/vacancies/2