server:
  servlet:
    context-path: /job-search/api/  # общий префикс для всех API
  port: 7878

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-228-209-117.eu-west-1.compute.amazonaws.com:5432/d66n7s83jl789u
    username: ewhaapdwpllmka
    password: 065a7dfd14d5562cf774811a11d240ad1eb8fbc3a4af0ac3db5b4cd64339597a
    platform: postgresql
    initialization-mode: never
    name: job-search
    continue-on-error: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
    enabled: true
  session:
    store-type: jdbc

logging:
  level:
    root: info
    org.springframework:
      web: debug
      security: off
      session: off
    ru.itfb.elib: debug
    org:
      hibernate:
        type: trace