version: 2.1

jobs:
  build:

    working_directory: ~/job-search

    docker:
      - image: circleci/openjdk:16-jdk-buster
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"

    steps:

      - checkout

      - restore_cache:
          key: job-search-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: job-search-{{ checksum "pom.xml" }}

      - run: |
          sudo apt-get install curl ca-certificates gnupg \
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc \| sudo apt-key add - \
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' \
          sudo apt-get update \
          sudo apt install postgresql-client-11 \
          pg_basebackup -V \
      - run: whoami
      - run: |
          psql -v ON_ERROR_STOP=1 --username postgres \<<-EOSQL \
            CREATE DATABASE "job-search" \
            WITH OWNER = postgres \
            ENCODING = 'UTF8' \
            TABLESPACE = pg_default \
            LC_COLLATE = 'en_US.utf8' \
            LC_CTYPE = 'en_US.utf8' \
            CONNECTION LIMIT = -1; \
          GRANT CONNECT, TEMPORARY ON DATABASE "job-search" TO public; \
          GRANT ALL ON DATABASE "job-search" TO postgres; \
          EOSQL

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/job-search-0.0.1-SNAPSHOT.jar